### ISSUE TITLE
Cannot run the web view

### ISSUE THREAD

**Issue by nicu-chiciuc** [edgedb/edgedb-studio#18]
Here are my steps:
1. `edgedb project upgrade --to-nightly`, so that my current version of edgedb is `2.0-dev.6629+7951e59`
2. Start in a quickstart project with `EDGEDB_DEBUG_HTTP_INJECT_CORS=1 edgedb instance start --foreground quickstart`
3. From `edgedb-studio` run `REACT_APP_EDGEDB_SERVER="127.0.0.1:10701" yarn start`

### What happens:
The ui starts and I can see my current database in the browser, I can click on it. But I don't see any data:
<img width="622" alt="Capture" src="https://user-images.githubusercontent.com/4076804/172024855-1569dac8-c487-4118-9aa6-699672186dca.PNG">

The request to `http://127.0.0.1:10701/ui/instance-info` return 200 OK with `{"instance_name": "quickstart", "databases": [{"name": "edgedb"}]}`

The request to `http://127.0.0.1:10701/db/edgedb/admin_binary_http` returns 200 OK with this error:
```
  File "edb/server/protocol/binary.pyx", line 1822, in edb.server.protocol.binary.EdgeConnection.main
  File "edb/server/protocol/binary.pyx", line 1446, in parse
  File "edb/server/protocol/binary.pyx", line 1373, in edb.server.protocol.binary.EdgeConnection.parse_prepare_query_part
edb.errors.BinaryProtocolError: empty query
```

### What I expect
I wanted the UI to connect to the database.

### What I tried
My plan was to test other nightly versions since I assumed that at least one of them might work. The problem is that I can't run 
````
edgedb server install --version "2.0-dev.6625+dcb9153"
```

since the cli returns
```
~/Dev/edgedb_learn/quickstart
❯ edgedb server install --version "2.0-dev.6625+dcb9153"
error: Invalid value "2.0-dev.6625+dcb9153" for '--version <version>': unsupported version format. Examples: `1.15`, `7`, `3.0-rc.1`

For more information try --help
```

I'm not sure what's the correct way to use a different nightly version for my instances.

**Comment by jaclarke** [comment]
This is a known issue, caused by recent protocol changes in edgedb nightly. There's a fix in this PR in edgedb-js: https://github.com/edgedb/edgedb-js/pull/354, however since it hasn't been merged yet, to make it work for now you'll need to build that branch of edgedb-js locally and `yarn link` it. Though we should have all this merged soon, and then `edgedb ui` bundled with the server will work correctly again.

**Comment by nicu-chiciuc** [comment]
ok, will probably wait until it's merged
