### ISSUE TITLE
UI updates

### ISSUE THREAD

**Issue by shougan** [edgedb/edgedb-studio#27]
[Figma](https://www.figma.com/file/430gInXr2xbFqBOLTCmpHJ/Cloud_UI?node-id=357%3A7018)

1. Pattern background for schema graph view( elements artboard )

![image](https://user-images.githubusercontent.com/1627031/179124694-c502a77c-bb30-4232-b785-e6f0742e8831.png)

2. Scheme light theme color update

![image](https://user-images.githubusercontent.com/1627031/179124728-68db0dfb-85d0-40e7-9413-dfd4dce693f1.png)

3. Title case “Inherited from”

![image](https://user-images.githubusercontent.com/1627031/179124755-7e4687b0-7f22-4b4c-8113-69bd9de14c33.png)

4. Changed code font weight to 500, and purple color to #B044C2

![image](https://user-images.githubusercontent.com/1627031/179124777-bcc37dc6-441a-4852-9aff-5160b1c2a86b.png)

5. Add a shadow to sticky object in code editor

![image](https://user-images.githubusercontent.com/1627031/179124815-76bdeebe-9af7-46a0-ace5-9328007c8002.png)
![image](https://user-images.githubusercontent.com/1627031/179124821-4cbab471-4cb6-4a3f-95da-264723055f74.png)

6. Search field focus state

![image](https://user-images.githubusercontent.com/1627031/179124844-bf827569-b893-45b4-a57f-86adc7d13820.png)
![image](https://user-images.githubusercontent.com/1627031/179124864-f53719b0-5354-4d2c-8ef7-f8c5603c297a.png)

7. Buttons margin update + icons for Schema view

![image](https://user-images.githubusercontent.com/1627031/179124900-b0c00729-ed72-4dc9-8ef7-5732ed4e9719.png)
![image](https://user-images.githubusercontent.com/1627031/179124902-8bee5ffb-d79d-4101-bcfc-4aa56b0f194c.png)
![image](https://user-images.githubusercontent.com/1627031/179124911-538b5977-0856-406b-84cc-cba07dc5573e.png)

8. Right aligned buttons for “Run” and “Persist Query”

![image](https://user-images.githubusercontent.com/1627031/179124949-7288aca4-08fe-4593-851f-5069afb78a3f.png)

9. Add buttons background for the frame top bar

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/1627031/179125028-baf7703e-d63d-466b-a469-b960ee13fd31.png">
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/1627031/179125061-6ecb058a-e86d-4615-8b73-8315f732e568.png">

10. Remove "Up arrow button" for popups

![image](https://user-images.githubusercontent.com/1627031/179125107-b16ba761-e8b5-4706-ba38-af48681ba9ff.png)
![image](https://user-images.githubusercontent.com/1627031/179125110-a70f9118-0c3f-403a-9643-65cfc4a14c1c.png)

11. Add Computed Link ":=" after name

<img width="375" alt="image" src="https://user-images.githubusercontent.com/1627031/179125240-dde0972e-38c1-4e4b-9f09-f18752359a2f.png">
<img width="493" alt="image" src="https://user-images.githubusercontent.com/1627031/179125288-a84d9e0b-28d2-483b-81a7-41dc740ddf91.png">

12. Add hover state for links in data explorer

![image](https://user-images.githubusercontent.com/1627031/179125322-161649a4-46e9-4bbc-a327-d262b46a17f8.png)
![image](https://user-images.githubusercontent.com/1627031/179125331-1a0f192a-44c8-4a27-b6a7-165ef3687da1.png)

13. Update Stats screen

![image](https://user-images.githubusercontent.com/1627031/179125390-c56a4bf0-b920-4ba8-a969-3d5ca1f46ecb.png)
![image](https://user-images.githubusercontent.com/1627031/179125399-ca69ba05-e2e0-4e74-bf4d-3948c5a34c47.png)

**Comment by 1st1** [comment]
On top of this:

* history integration for schema & data browsers 

* sync with the system theme by default like we do on docs. (maybe we reuse the theme switching widget, @shougan?)

**Comment by shougan** [comment]
> On top of this:
> 
>     * history integration for schema & data browsers
> 
>     * sync with the system theme by default like we do on docs. (maybe we reuse the theme switching widget, @shougan?)

It's a separate [issue](https://github.com/edgedb/edgedb-studio/issues/26), and by design, the switcher is on the bottom of left sidebar. And yes, let's reuse switcher widget.

**Comment by jaclarke** [comment]
Closed by #28
